name: HandleStaleDiscussions
on:
  schedule:
    - cron: '0 */4 * * *'
  discussion_comment:
    types: [created]

jobs:
  handle-stale-discussions:
    name: Handle stale discussions
    runs-on: ubuntu-latest
    steps:
      - name: Stale discussions action
        uses: aws-github-ops/handle-stale-discussions@main
        env:
          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
